blog/urls.py
# -*-coding: utf-8 -*-
#!/usr/bin/env python
from __future__ import unicode_literals
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'todo.views.home', name='home'),
    #url(r'^$', include('todo.urls')),
    url(r'^todos/', include('todo.urls')),
    #此处不能以$结尾
    url(r'^book/', include('books.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^grappelli/',include('grappelli.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^online/', include('online.urls')),
    #url(r'^__debug__/', include(debug_toolbar.urls)),
)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),

    )

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

blog/views.py
from django.shortcuts import render_to_response
import MySQLdb
import datetime
from system.models import Role
def hello(request):
    return render_to_response("hello.html")
def current_datetime(request):
    current_date = datetime.datetime.now()
    current_section = "header nav"
    return render_to_response('current_datetime.html', locals())

def hours_ahead(request, offset):
    hour_offset = int(offset)
    a = 2014
    next_time = hour_offset + a
    return render_to_response('hours_ahead.html', locals())

def list_user(request):
    #db = MySQLdb.connect(user="root", db="test", passwd="abc123", host="localhost")
    #cursor = db.cursor()
    #cursor.execute('select * from role')
    #names = [row[1] for row in cursor.fetchall()]
    names = Role.objects.order_by('id')
    #db.close()
    return render_to_response('list_user.html', locals())

contact/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from system.models import Role
from django.core.mail import send_mail
from contact.forms import ContactForm

# Create your views here.
def contact(request):
    errors = []
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
        else:
            form = ContactForm()
    return render_to_response('contact_form.html', {'form': form})

blog/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <h1>Welcome to this page</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

blog/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

   <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

blog/templates/current_datetime.html
{% extends "base.html" %}
{% block title %} current_date {% endblock %}
{% block content %}
    <p>It is now {{ current_date }}.</p>
{% endblock%}
{% block footer %}
    current bottom
{% endblock %}

blog/templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future time block{% endblock %}

{% block content %}
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}
{% block footer %}
    hours_ahead bottom
{% endblock %}

blog/templates/list_todo1.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %} BLOG List ToDo {% endblock %}</title>
</head>
<body>
    xxxxx ---  blog
</body>
</html>

blog/templates/list_user.html
{% extends 'base.html' %}
{% block title %} list User {% endblock %}
{% block content %}
{% for m in names %}
   <a>{{m.role_name}}</a>
   {% endfor %}
{% endblock %}

blog/templates/nav.html
<div id="nav">
    You are in: {{ current_section }}
</div>

blog/templates/search_form.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
{% if error %}
<p style="color: red;">Please submit a search term 20 characters or shorter.</p>
{% endif %}
 <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
 </form>
</body>
</html>

blog/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>
{% if list %}
    <p>Found {{ list|length }} list {{ list|pluralize }}.</p>
    <ul>
            {% for item in list %}
            <li>{{ book.role_name }}</li>
            {% endfor %}
        </ul>
    {% else %}
    <p>No books matched your search criteria.</p>
{% endif %}